      parameter(MMAX=1000000)   ! max nonzero in row of a (non-MPI)
      parameter(MPIX=150000000) ! max dimension of array segments
      parameter(NMAX=25000000)  ! max data vector (incl. damping zeros)
      parameter(NDIM=1000000)   ! max model dimension (incl. corrections)
      parameter(NXTRY=50)      ! max trials for chi2 convergence
      parameter(NBR=100)     ! max number of nearest neighbours
      parameter(NFN=128)     ! max length of file name
      parameter(NOUT=200000) ! max nr of outliers
      parameter(MPROC=264)    ! max nr of processors for MPI
      parameter(NPMAX=400000) ! number of model grid nodes
